// <auto-generated />
namespace CSKH_Sungroup_BT3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Donnt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Donnt));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210255537_Donnt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
